# Position Controllers ---------------------------------------
ud_gripper_mount_controller:
      type: effort_controllers/JointPositionController
      joint: ud_gripper_mount_joint
      pid: {p: 1.0, i: 1.0, d: 1.0}
